version: '3.8'

services:
  p2cfrontend:
    build: .
    ports:
      - "8004:80"
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"